apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 295devops-argo-application
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: "https://github.com/dsantafe/295devops-jenkins-challenge-gitops"
    path: dev
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: 295devops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true